<a href="https://colab.research.google.com/github/namratesh/Machine-Learning/blob/master/1_Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
%tensorflow_version 1.x
import tensorflow as tf


In [0]:
#creating sess
sess = tf.Session()

In [0]:
# declaring tensors and placehoolders
x_vals = np.array([1., 3., 4., 5., 9.])
x_data = tf.placeholder(tf.float32)
m_const = tf.constant(5.)

In [0]:
#mltiplication
my_prod = tf.multiply(x_data,m_const)
for x_val in x_vals:
  print(sess.run(my_prod, feed_dict= {x_data:x_val}) )

5.0
15.0
20.0
25.0
45.0


#matrix multplication

In [0]:

#creating 3*5 matrix
my_arr = np.array([[1., 3., 4., 6., 7.],
                   [-2., 3., 4., 5., 6.],
                   [5., 6., 7., 2., 3.]])
my_arr

array([[ 1.,  3.,  4.,  6.,  7.],
       [-2.,  3.,  4.,  5.,  6.],
       [ 5.,  6.,  7.,  2.,  3.]])

In [0]:
x_vals = np.array([my_arr, my_arr+1])
x_data = tf.placeholder(tf.float32, shape=(3,5))

#creating constant that will be used for multiplication and addition

In [0]:
m1 = tf.constant([[2.], [5.], [6.], [0.], [6.]])
m2 = tf.constant([[5.]])
a1 = tf.constant([[10.]])

In [0]:
prod1 = tf.matmul(x_data, m1) #multiplication
prod2 = tf.matmul(prod1,m2) #addition
add1 = tf.add(prod2, a1)  #multiplication

In [0]:
print(prod1)
print(add1)
print(prod2)

Tensor("MatMul:0", shape=(3, 1), dtype=float32)
Tensor("Add:0", shape=(3, 1), dtype=float32)
Tensor("MatMul_1:0", shape=(3, 1), dtype=float32)


In [0]:
#addition
for x_val in x_vals:
  print(sess.run(add1, feed_dict={x_data:x_val}))

[[425.]
 [365.]
 [510.]]
[[520.]
 [460.]
 [605.]]


In [0]:
#multiplication
for x_val in x_vals:
  print(sess.run(prod1, feed_dict={x_data:x_val}))

[[ 83.]
 [ 71.]
 [100.]]
[[102.]
 [ 90.]
 [119.]]


In [0]:
#multiplication
for x_val in x_vals:
  print(sess.run(prod2, feed_dict={x_data:x_val}))

[[415.]
 [355.]
 [500.]]
[[510.]
 [450.]
 [595.]]


Working with multiple layers

In [0]:
#Creating 2d image using numpy
x_shape = [1,4,4,1]
x_val = np.random.uniform(size=x_shape)

In [0]:
#creating placeholder in graph to feed sample image
x_data = tf.placeholder(tf.float32, shape=x_shape)

In [0]:
my_filter = tf.constant(0.25, shape = [4,6,1,1])
my_strides = [1,2,2,1]
mov_avg_layer = tf.nn.conv2d(x_data, my_filter, my_strides, padding= 'SAME''',name = 'Movong_Avg_Window' )

In [0]:
def custom_layer(input_matrix):
  input_matrix_squeezed = tf.squeeze(input_matrix)
  A = tf.constant([[1., 2.], [-1., 3.]])
  B =  tf.constant(1., shape=[2, 2])
  temp1 = tf.matmul(A, input_matrix_squeezed)
  temp = tf.add(temp1, B) # Ax + b
  return(tf.sigmoid(temp))


In [0]:
with tf.name_scope('Custom_Layer') as scope:
 custom_layer1 = custom_layer(mov_avg_layer)

In [0]:
print(sess.run(custom_layer1, feed_dict={x_data: x_val}))


[[0.99798125 0.99798125]
 [0.9888538  0.9888538 ]]


In [0]:
#importing numpy and tensorflow
import numpy as np
%tensorflow_version 1.x
import tensorflow as tf

# declaring tensors and placehoolders
x_vals = np.array([1., 3., 4., 5., 9.])
x_data = tf.placeholder(tf.float32)

#declaring constant
m_const = tf.constant(5.)

#creating sess
sess = tf.Session()

#multiplication of 1D array 
my_prod = tf.multiply(x_data, m_const)
print("multilplication of 1d array:")
for x_val in x_vals:
  print(sess.run(my_prod, feed_dict= {x_data:x_val}) )
print("*"*30)

#addiditon of 1D array
my_add = tf.add(x_data, m_const)
print("addition of 1d array:")
for x_val in x_vals:
  print(sess.run(my_add, feed_dict= {x_data:x_val}) )


multilplication of 1d array:
5.0
15.0
20.0
25.0
45.0
******************************
addition of 1d array:
6.0
8.0
9.0
10.0
14.0


In [0]:
#importing numpy and tensorflow
import numpy as np
%tensorflow_version 1.x
import tensorflow as tf

#Creating 2d image using numpy
x_shape = [1,4,4,1]
x_val = np.random.uniform(size=x_shape)

#creating placeholder in graph to feed sample image
x_data = tf.placeholder(tf.float32, shape=x_shape)

my_filter = tf.constant(0.25, shape = [4,6,1,1])
my_strides = [1,2,2,1]
mov_avg_layer = tf.nn.conv2d(x_data, my_filter, my_strides, padding= 'SAME'''
                                                    ,name = 'Movong_Avg_Window')

# define a custom layer that will operate on the 2x2 output of the moving
# window averagecustom function will first multiply the input by another 2x2
# matrix tensor, and then add one to each entry
def custom_layer(input_matrix):
  input_matrix_squeezed = tf.squeeze(input_matrix)
  A = tf.constant([[1., 2.], [-1., 3.]])
  B =  tf.constant(1., shape=[2, 2])
  temp1 = tf.matmul(A, input_matrix_squeezed)
  temp = tf.add(temp1, B) # Ax + b
  return(tf.sigmoid(temp))

with tf.name_scope('Custom_Layer') as scope:
 custom_layer1 = custom_layer(mov_avg_layer)

print(sess.run(custom_layer1, feed_dict={x_data: x_val}))


[[0.99621516 0.99621516]
 [0.97804    0.97804   ]]
