In [1]:
import numpy as np

In [2]:
a = 1 #scalar

In [6]:
b = np.array([1, 2, 3, 4])  #vector
b

array([1, 2, 3, 4])

In [7]:
c = np.array([         #matrix
                [1, 2, 3, 4],
                [5, 6, 7, 8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
d = np.array([
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [10,11,21,34],
                [12,32,31,34]])

d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 21, 34],
       [12, 32, 31, 34]])

### Matrix Addition

In [10]:
a =np.array([ [3, 8], [4, 6] ])
b =np.array([ [4, 0], [1, -9]])
a+b

array([[ 7,  8],
       [ 5, -3]])

### Matrix Subtraction

In [11]:
a =np.array([ [3, 8], [4, 6] ])
b =np.array([ [4, 0], [1, -9]])
a-b

array([[-1,  8],
       [ 3, 15]])

### Matrix Multiplication

In [15]:
#  by constant
a =np.array([ [4, 0], [1,-9 ]]) 
2*a

array([[  8,   0],
       [  2, -18]])

In [22]:
#dot multiplication
x = np.array([[1, 2, 3],
     [4, 5, 6] ])
y = np.array([[7, 8],
     [9, 10],
     [11, 12]])
x.dot(y)

array([[ 58,  64],
       [139, 154]])

In [23]:
#Transpose matrix
a = np.array([[6, 4, 24],
            [1, -9, 8]])
a.T

array([[ 6,  1],
       [ 4, -9],
       [24,  8]])

In [20]:
y

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])