In [1]:
import numpy as np

In [2]:
#1-d array
a = np.array([12,34,35,56])

In [3]:
a

array([12, 34, 35, 56])

In [4]:
#2-d array
b = np.array([ 
             [1,2,3],
             [2,5,6]
            ])

In [5]:
b

array([[1, 2, 3],
       [2, 5, 6]])

In [6]:
a.shape #shape

(4,)

In [7]:
b.shape

(2, 3)

In [8]:
a.ndim  #dimension

1

In [9]:
b.ndim

2

In [10]:
a.dtype   #type

dtype('int32')

In [11]:
b.dtype

dtype('int32')

In [12]:
len(a)

4

In [13]:
len(b)   #len

2

In [14]:
c = np.arange(6) 

In [15]:
c

array([0, 1, 2, 3, 4, 5])

In [16]:
d = np.arange(1,15,3)

In [17]:
d

array([ 1,  4,  7, 10, 13])

### Arithmetic operation

In [20]:
a = np.array([2,3,4,5])
b = np.array([3,4,5,6])

In [21]:
a+b 

array([ 5,  7,  9, 11])

In [22]:
a-b

array([-1, -1, -1, -1])

In [23]:
a*b

array([ 6, 12, 20, 30])

In [24]:
a/b

array([0.66666667, 0.75      , 0.8       , 0.83333333])

### Logical operation

In [25]:
a = np.array([0,1,1,0], dtype = bool)
b = np.array([1,1,1,0], dtype = bool)

In [27]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [28]:
np.logical_and(a,b)

array([False,  True,  True, False])

In [29]:
np.logical_not(a,b)

array([ True, False, False,  True])

AttributeError: module 'numpy' has no attribute 'logical_nand'

### Transcendental functions

In [31]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [32]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [33]:
np.log(a)

C:\Users\91998\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [34]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

### Reductions

In [40]:
a = np.array([0,5,6,7])
a

array([0, 5, 6, 7])

In [41]:
np.sum(a)

18

In [50]:
a = np.array([[1,2,3,4],[5,9,7,8]])
a

array([[1, 2, 3, 4],
       [5, 9, 7, 8]])

In [43]:
np.sum(a, axis=1)  #row sum

array([10, 26])

In [44]:
np.sum(a,axis=0) #column sum

array([ 6,  8, 10, 12])

In [45]:
np.max(a) #maximum value in array

8

In [46]:
np.min(a) #minimum value in array

1

In [51]:
np.argmax(a) #index of maximum element

5

In [49]:
np.argmin(a) #index of minimum element

0

### Statistics

In [52]:
a = np.array([1,2,3,4,5,6,7])              

In [53]:
np.mean(a) #mean

4.0

In [55]:
np.median(a) #median

4.0

In [56]:
np.std(a)  #standord deviation

2.0

### Linear Algebra

In [58]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])  
a

array([[1., 2.],
       [3., 4.]])

In [59]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [60]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [65]:
a@a       # matrix product

array([[ 7., 10.],
       [15., 22.]])

In [69]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))